version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql_container
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=flask-db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
  service1:
    container_name: "generator_service1"
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 3
  service2:
    container_name: "generator_service2"
    build: ./service2
    deploy:
      replicas: 3
volumes:
    db-data:
