version: '3.7'
services:
  database:
    container_name: mysql_container
    image: abusyd1/data-db:latest
    build: ./db
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=flask-db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql

  service1:
    container_name: "generator_service1"
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 3
  service2:
    container_name: "generator_service2"
    build: ./service2
    deploy:
      replicas: 3
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
volumes:
    db-data:
