version: '3.7'
services:
  service1:
    container_name: "generator_service1"
    image: abusyd1/service1:latest
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 3
  service2:
    container_name: "generator_service2"
    image: abusyd1/service2:latest
    build: ./service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 3
  service3:
    container_name: "generator_service3"
    image: abusyd1/service3:latest
    build: ./service3
    ports: 
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
      replicas: 3
  service4:
    container_name: "generator_service4"
    image: abusyd1/service4:latest
    build: ./service4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
      replicas: 3
