version: '3.7'
services:
  service1:
    container_name: "generator_service1"
    build: ./service1
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root@localhost/Project2"
    deploy:
      replicas: 3
  service2:
    container_name: "generator_service2"
    build: ./service2
    deploy:
      replicas: 3
