version: '3.7'
services:
  database:
    container_name: mysql_container
    image: abusyd1/data-db:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=flask-db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql

  service1:
    container_name: "generator_service1"
    image: abusyd1/service1:latest
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 3
  service2:
    container_name: "generator_service2"
    image: abusyd1/service2:latest
    build: ./service2
    deploy:
      replicas: 3
  service3:
    container_name: "generator_service3"
    image: abusyd1/service3:latest
    build: ./service3
    deploy:
      replicas: 3
  service4:
    container_name: "generator_service4"
    image: abusyd1/service4:latest
    build: ./service4
    deploy:
      replicas: 3
volumes:
    db-data:
